name: Auto Build Blog on Push of source branch

on:
  workflow_dispatch:
      # For manually trigger:
      # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-py3-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-py3-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Build and publish blog
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |-
        make ci
