name: Auto Build Blog on Push of source branch

on:
  workflow_dispatch:
      # For manually trigger:
      # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.5.4'
        cache: 'pip' # caching pip dependencies
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Build and publish blog
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |-
        make ci
